#! /usr/bin/env python
# coding: utf-8
"""
Contains a MainMenu, with all of the configuaration variables defined.
The Gui class simple instantiates the MainMenu and handles window switching.
 - WCW 181127
"""
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

import platform
if 'darwin' in platform.system().lower():
    import matplotlib
    matplotlib.use('TkAgg') #Mac support
    
import matplotlib.pyplot as plt

if __package__ in [None,""]:
    #Running from git clone
    from daq import *
    from menu import TwoPaneWindow
else:
    #Running from pip install
    from .daq import *
    from .menu import TwoPaneWindow



#Gui's in general have a lot of boiler plate code.
class Gui(QApplication):
    def __init__(self):
        super(Gui,self).__init__(['Probecardv1.4 DAQ'])

    def addMenu(self,menuWindow):
        self.window = menuWindow
        self.window.onExperiment.connect(self.startExperiment)
        self.aboutToQuit.connect(self.window.exit)
        self.exec_()
    def startExperiment(self,msg):
        self.window.saveSettings()
        options = self.window.getData() #Menu options
        self.window.close()
        print(options)
        if msg=='single':
            self.window=BasicDaqWindow() #QWindow
            self.daq=SinglePixelDaq(options) #QThread
            self.daq.newData.connect(self.window.addPoint)
            self.daq.start()
            self.window.show()
        elif msg == 'multi':
            self.window = MultiPixelDaq(data)
            self.window.onFinish.connect(self.restore)
        elif msg=='all':
            print(msg)
        elif msg=='calib':
            print(msg)
        else:
            print("error: wrong init.",msg)
            
    def restore(self,msg):
        self.window = MainMenu()
        self.window.onExperiment.connect(self.startExperiment)
        self.aboutToQuit.connect(self.window.exit)


def five():
    return 6

if __name__ == "__main__":
    states={
        'single': 'Single Pixel',
        'multi': 'Multi Pixels',
        'all': 'Total Current',
        'calib': 'Calibration',
    }
    options=[
        ('Email', 'email','name@email.com'),
        ('Experiment Name (for excel)', 'filename','filename'),
        ('Keithley Compliance (A)', 'kcomp'),
        ('Probecard controller COM port (#)',   'com'),
        ('Agilent Hold Time (sec)', 'holdTime'),
    ]
    gui=Gui()
    menuWindow=TwoPaneWindow(options,states)
    menuWindow.addStateWidget(states['multi'],(QLabel('Agilent Compliance (A)'),menuWindow.getLineEdit('acomp')))
    gui.addMenu(menuWindow)

